### ISSUE TITLE
Conversation: Render thread messages on navigation

### ISSUE THREAD

**Issue by krishokr** [PersonaFlow/agentstack#86]
## Todo

- [ ] Create component layout
- [ ] Handle conversation navigation
- [ ] Display messages in page
